defaults:
  - data_manipulations@equal_gaus_features: equal_gaus_features
  - data_manipulations@save_raw_features: save_raw_features
  - data_manipulations@CombinedPSEs: combined_encodings
  - liftings@_here_: ${get_required_lifting:graph,${model}}
